name: STP Snapshot

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Regenerate STP snapshot
        run: |
          mkdir -p dist
          python tools/stp_make.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: stp-artifacts
          path: dist/*

      - name: Commit back updated dist
        if: github.actor != 'github-actions[bot]'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f dist/stp.yaml dist/prompt_pack.md
          if git diff --cached --quiet; then
            echo "No changes in dist/*"
          else
            git commit -m "ci: update STP artifacts [skip ci]"
            git push
          fi
